name: mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - mlflow=2.15.1
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - hyperopt==0.2.7
  - seaborn
  - py-xgboost

