stages:
  prepare:
    cmd: python src/create_features_w_params.py
    deps:
      - data/adult.data
      - data/adult.test
      - src/create_features_w_params.py
    params: 
      - features.chi2percentile
      - features.train_path
      - features.test_path
    outs:
      - data/pipeline.pkl
      - data/processed_train_data.csv
      - data/processed_test_data.csv

  prepare_income:
    cmd: python src/preprocessing.py
    deps:
      - data/IncomeSurveyDataset.csv
      - src/preprocessing.py
    params: 
      - features.chi2percentile
      - features.income_path
    outs:
      - data/pipeline_income.pkl
      - data/processed_income_data.csv