stages:
  prepare:
    cmd: python create_features_w_params.py
    deps:
      - data/adult.data
      - data/adult.test
      - create_features_w_params.py
    params: 
      - features.chi2percentile
      - features.train_path
      - features.test_path
    outs:
      - data/pipeline.pkl
      - data/processed_train_data.csv
      - data/processed_test_data.csv